#!/usr/bin/env python3
"""Emit an HTML report for an MLPerf training sweep.

Usage:
    python3 tools/report.py --logs <results_dir> --out report.html

Renders a single-file HTML (no external assets beyond inline CSS + a data
URI for the chart). Parses MLLOG events from every result_*.txt in the
given directory.
"""
from __future__ import annotations

import argparse
import base64
import html
import io
import json
import math
import re
import sys
from pathlib import Path
from typing import Any

MLLOG_RE = re.compile(r":::MLLOG\s*(\{.*\})")


def parse_log(path: Path) -> dict[str, Any]:
    events: list[dict[str, Any]] = []
    with path.open(errors="replace") as f:
        for line in f:
            m = MLLOG_RE.search(line)
            if not m:
                continue
            try:
                events.append(json.loads(m.group(1)))
            except Exception:
                continue
    run_starts = [e for e in events if e.get("key") == "run_start"]
    run_stops = [e for e in events if e.get("key") == "run_stop"]
    eval_evs = [e for e in events if e.get("key", "").startswith("eval_")]
    seed = next((e["value"] for e in events if e.get("key") == "seed"), None)
    gbs = next((e["value"] for e in events if e.get("key") == "global_batch_size"), None)
    lr = next((e["value"] for e in events if e.get("key") == "opt_base_learning_rate"), None)
    opt = next((e["value"] for e in events if e.get("key") == "opt_name"), None)
    ttt_s = None
    if run_starts and run_stops:
        t0 = run_starts[0].get("time_ms") or 0
        t1 = run_stops[-1].get("time_ms") or 0
        if t0 and t1 and t1 > t0:
            ttt_s = (t1 - t0) / 1000.0
    status = run_stops[-1].get("metadata", {}).get("status") if run_stops else None
    final_eval = eval_evs[-1]["value"] if eval_evs else None
    return dict(
        path=str(path),
        seed=seed,
        global_batch_size=gbs,
        learning_rate=lr,
        optimizer=opt,
        time_to_train_s=ttt_s,
        final_eval=final_eval,
        run_stop_status=status,
        events_n=len(events),
    )


def svg_chart(values: list[float]) -> str:
    if not values:
        return "<p>(no time-to-train samples)</p>"
    w, h, pad = 480, 160, 24
    xs = list(range(1, len(values) + 1))
    mx = max(values)
    mn = min(values)
    if mx == mn:
        mx = mn + 1
    def x(i): return pad + (i - 1) * (w - 2 * pad) / max(1, len(values) - 1)
    def y(v): return h - pad - (v - mn) * (h - 2 * pad) / (mx - mn)
    pts = " ".join(f"{x(i):.1f},{y(v):.1f}" for i, v in zip(xs, values))
    bars = "".join(
        f'<rect x="{x(i)-6:.1f}" y="{y(v):.1f}" width="12" height="{h-pad-y(v):.1f}" fill="#76B900"/>'
        for i, v in zip(xs, values)
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
        f'<rect width="{w}" height="{h}" fill="#f8f8f8"/>'
        f'{bars}'
        f'<polyline fill="none" stroke="#333" stroke-width="1.5" points="{pts}"/>'
        f'<text x="{pad}" y="{h-4}" font-size="10">run #</text>'
        f'<text x="{w-4}" y="{h-4}" font-size="10" text-anchor="end">min={mn:.1f}s max={mx:.1f}s</text>'
        f'</svg>'
    )


def render(summaries: list[dict[str, Any]], title: str) -> str:
    rows = []
    for s in summaries:
        rows.append(
            "<tr>"
            + "".join(
                f"<td>{html.escape(str(s.get(k, '')))}</td>"
                for k in (
                    "path",
                    "seed",
                    "optimizer",
                    "global_batch_size",
                    "learning_rate",
                    "time_to_train_s",
                    "final_eval",
                    "run_stop_status",
                )
            )
            + "</tr>"
        )
    tts = [s["time_to_train_s"] for s in summaries if s.get("time_to_train_s")]
    if tts:
        geomean = math.exp(sum(math.log(t) for t in tts) / len(tts))
    else:
        geomean = None
    chart = svg_chart(tts)
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>
  body {{ font: 14px system-ui, sans-serif; margin: 2em; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1em; }}
  th, td {{ border: 1px solid #ccc; padding: 4px 8px; font-size: 13px; }}
  th {{ background: #eee; text-align: left; }}
  h1 {{ margin-bottom: 0.2em; }}
  .meta {{ color: #666; font-size: 12px; }}
  .kpi {{ display: inline-block; padding: 0.5em 1em; background: #f4f4f4;
           margin-right: 0.5em; border-left: 3px solid #76B900; }}
</style>
</head><body>
<h1>{html.escape(title)}</h1>
<p class="meta">Generated by <code>tools/report.py</code> &mdash; parsed {sum(s['events_n'] for s in summaries)} MLLOG events across {len(summaries)} logs.</p>
<div>
  <span class="kpi">runs: <b>{len(summaries)}</b></span>
  <span class="kpi">geomean TTT: <b>{f'{geomean:.1f} s' if geomean else 'n/a'}</b></span>
</div>
<h2>Time-to-train per run</h2>
{chart}
<h2>Per-run table</h2>
<table>
<thead><tr>
  <th>log</th><th>seed</th><th>optimizer</th><th>GBS</th><th>LR</th>
  <th>TTT (s)</th><th>final_eval</th><th>status</th>
</tr></thead>
<tbody>
{''.join(rows)}
</tbody></table>
</body></html>"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--logs", required=True, help="directory containing result_*.txt")
    ap.add_argument("--out", required=True, help="output HTML path")
    ap.add_argument("--title", default="MLPerf Training Report")
    args = ap.parse_args()
    logs = sorted(Path(args.logs).glob("result_*.txt"))
    if not logs:
        print(f"no result_*.txt in {args.logs}", file=sys.stderr)
        return 1
    summaries = [parse_log(p) for p in logs]
    Path(args.out).write_text(render(summaries, args.title), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
